// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/config/employee-costs': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/config/employee-costs.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/config/employee-costs.post').default>>>>
    }
    '/api/config/employee-costs/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/config/employee-costs/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/config/employee-costs/[id].put').default>>>>
    }
    '/api/dict/expense-categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dict/expense-categories.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dict/expense-categories.post').default>>>>
    }
    '/api/dict/expense-categories/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dict/expense-categories/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dict/expense-categories/[id].put').default>>>>
    }
    '/api/dict/purchase-contents': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dict/purchase-contents.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dict/purchase-contents.post').default>>>>
    }
    '/api/dict/purchase-contents/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dict/purchase-contents/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dict/purchase-contents/[id].put').default>>>>
    }
    '/api/projects': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects.post').default>>>>
    }
    '/api/projects/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[id].put').default>>>>
    }
    '/api/projects/:id/copy': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[id]/copy.post').default>>>>
    }
    '/api/projects/:id/export': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[id]/export.get').default>>>>
    }
    '/api/projects/:id/status': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[id]/status.put').default>>>>
    }
    '/api/projects/:projectId/records': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[projectId]/records.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[projectId]/records.post').default>>>>
    }
    '/api/records': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/records.get').default>>>>
    }
    '/api/records/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/records/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/records/[id].put').default>>>>
    }
    '/api/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stats.get').default>>>>
    }
    '/api/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload.post').default>>>>
    }
    '/api/upload/:filename': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload/[filename].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload/[filename].get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}